
<h2>This is a test Main Generated by TemplateIndex</h2>
        	<p>&nbsp;</p>
           	<p>&nbsp;</p>
       	  <h3>This data was sent by model</h3>
          <p>BlaBlabla:</p>
            <ul>
                <li><?php echo $params?></li>
                <li>My name is: <?php echo $name?></li>
                <li>And I'm <?php echo $age?> YO.</li>
            </ul>